@RiverBooks.Web_HostAddress = https://localhost:7179

GET {{RiverBooks.Web_HostAddress}}/books
Accept: application/json

###

@BookID=a89f6cd7-4693-457b-9009-02205dbbfe45
GET {{RiverBooks.Web_HostAddress}}/books/{{BookID}}
Accept: application/json

###

POST {{RiverBooks.Web_HostAddress}}/books
Accept: application/json
Content-Type: application/json

{
  "id": "b89f6cd7-4693-457b-9009-02205dbbfe45",
  "title": "Modular Monoliths - Getting Started",
  "author": "Steve Smith",
  "price": 29.99
}

###

# Test the location header
GET {{RiverBooks.Web_HostAddress}}/books/b89f6cd7-4693-457b-9009-02205dbbfe45
Accept: application/json

###

DELETE {{RiverBooks.Web_HostAddress}}/books/b89f6cd7-4693-457b-9009-02205dbbfe45
Accept: application/json

###

POST {{RiverBooks.Web_HostAddress}}/books/b89f6cd7-4693-457b-9009-02205dbbfe45/pricehistory
Accept: application/json
Content-Type: application/json

{
  "newPrice": 19.99
}

###

# CREATE USER

POST {{RiverBooks.Web_HostAddress}}/users
Accept: application/json
Content-Type: application/json

{
  "email":"steve3@test.com",
  "password":"Pass@word1"
}

###

# LOGIN

POST {{RiverBooks.Web_HostAddress}}/users/login
Accept: application/json
Content-Type: application/json

{
  "email":"steve2@test.com",
  "password":"Pass@word1"
}

###

@token=eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbEFkZHJlc3MiOiJzdGV2ZTJAdGVzdC5jb20iLCJpYXQiOjE3MDg0ODQ3NjEsImV4cCI6MTcwODQ4ODM2MSwibmJmIjoxNzA4NDg0NzYxfQ.bR4zGFyl_rKj3_D1YEKZFIBcKDPX7LsHHPXQPdK4ceU

# Add item to cart
POST {{RiverBooks.Web_HostAddress}}/cart
Accept: text/plain
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "bookId":"a89f6cd7-4693-457b-9009-02205dbbfe45",
  "quantity":10
}

###

# List items in cart
GET {{RiverBooks.Web_HostAddress}}/cart
Accept: application/json
Authorization: Bearer {{token}}

###

# List All Orders
GET {{RiverBooks.Web_HostAddress}}/orders
Accept: application/json
Authorization: Bearer {{token}}

###

# Checkout Cart
POST {{RiverBooks.Web_HostAddress}}/cart/checkout
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "shippingAddressId":"1184ecab-f236-43e9-a48c-a5b9bc59ad11",
  "billingAddressId":"1184ecab-f236-43e9-a48c-a5b9bc59ad11"
}

###

# List Addresses

GET {{RiverBooks.Web_HostAddress}}/users/addresses
Accept: application/json
Authorization: Bearer {{token}}

###

# Add Address to User
POST {{RiverBooks.Web_HostAddress}}/users/addresses
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "street1": "2 Main St.",
  "street2": "Number 722",
  "city":"Anytown",
  "state":"OH",
  "postalCode":"12345-6789",
  "country":"USA"
}

###

# FLUSH CACHE

POST {{RiverBooks.Web_HostAddress}}/flushcache
Accept: application/json
Content-Type: application/json

{
}

###

# LIST EMAILS

GET {{RiverBooks.Web_HostAddress}}/emails
Accept: application/json
Authorization: Bearer {{token}}

###

# TOP SALES 1 - REACH IN REPORTING

GET {{RiverBooks.Web_HostAddress}}/topsales?month=2&year=2024
Accept: application/json

###

# TOP SALES 2 - EVENT INGESTION CUSTOM DB

GET {{RiverBooks.Web_HostAddress}}/topsales2?month=2&year=2024
Accept: application/json

###